import type { SiteConfig } from "@/types/site-config";
import { topLevelBlockSectionId } from "@/lib/utils";

const now = "2026-07-03T00:00:00.000Z";

export const defaultSiteConfig: SiteConfig = {
  version: 1,
  profile: {
    avatarUrl: "/default-avatar.svg",
    displayName: "林荣威",
    username: "lrwei91",
    headline: "测试工程师（游戏 / Web 业务测试 · 自动化 · 版本质量）",
    bio: "10 年游戏与 Web 项目经历，4 年专职游戏测试。熟悉需求评审 → 测试分析 → 环境与数据准备 → 功能验证 → 缺陷闭环 → 回归与版本验收完整流程。擅长业务规则、状态流转、配置数据和异常边界设计验证场景。",
    location: "福建福州",
    tags: ["测试", "自动化", "Playwright", "AI QA", "游戏测试"],
    email: "lrwei91@gmail.com",
    socialLinks: [
      {
        id: "github",
        label: "GitHub",
        icon: "github",
        href: "https://github.com/lrwei91",
        isVisible: true,
        sortOrder: 1
      },
      {
        id: "email",
        label: "Email",
        icon: "mail",
        href: "mailto:lrwei91@gmail.com",
        isVisible: true,
        sortOrder: 2
      }
    ],
    moduleOrder: [
      "avatar",
      "name",
      "headline",
      "bio",
      "tags",
      "location",
      "socialLinks",
      "contact"
    ],
    visibleModules: {
      avatar: true,
      name: true,
      headline: true,
      bio: true,
      tags: true,
      location: true,
      socialLinks: true,
      contact: true,
      latestPosts: false
    }
  },
  sections: [],
  blocks: [
    {
      id: "text-summary",
      sectionId: topLevelBlockSectionId,
      title: "个人总结",
      subtitle: "Professional Summary",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "user",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "summary",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 1,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "summary-content",
      sectionId: topLevelBlockSectionId,
      title: " ",
      subtitle: "",
      description: "拥有 10 年游戏与 Web 项目经历，其中 4 年专职游戏测试；熟悉「需求评审 → 测试分析 → 环境与数据准备 → 功能验证 → 缺陷闭环 → 回归与版本验收」完整流程。\n\n长期参与用户、充提系统、活动、任务、分销佣金、后台管理等业务模块的质量保障，擅长从业务规则、状态流转、配置数据和异常边界设计验证场景。\n\n作为测试团队 AI QA 全链路推进主要负责人，基于 Codex Skills + Playwright 构建覆盖需求分析、用例生成、脚本执行、证据回填、Bug 登记/验证与知识库同步的七阶段工作流，实现测试过程与交付结果可追溯。",
      size: "wide",
      coverImage: "",
      icon: "",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        textVariant: "plain",
        textAlign: "left",
        textBold: false
      },
      isVisible: true,
      isFeatured: false,
      sortOrder: 2,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-skills",
      sectionId: topLevelBlockSectionId,
      title: "核心技能",
      subtitle: "Core Skills",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "zap",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "skills",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 3,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-test",
      sectionId: topLevelBlockSectionId,
      title: "测试分析与执行",
      subtitle: "",
      description: "需求评审、测试计划、用例设计、环境与数据准备、功能/回归测试、版本验收",
      size: "small-square",
      coverImage: "",
      icon: "check",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 4,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-game",
      sectionId: topLevelBlockSectionId,
      title: "游戏专项测试",
      subtitle: "",
      description: "热更新、兼容性、弱网、海外版本、客户端/服务端配置、Unity 资源与 UGUI 界面验证",
      size: "small-square",
      coverImage: "",
      icon: "gamepad",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 5,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-biz",
      sectionId: topLevelBlockSectionId,
      title: "业务专项测试",
      subtitle: "",
      description: "用户体系、充提系统、充值活动、任务、多级分销、佣金结算、后台管理",
      size: "small-square",
      coverImage: "",
      icon: "briefcase",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 6,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-automation",
      sectionId: topLevelBlockSectionId,
      title: "自动化与持续集成",
      subtitle: "",
      description: "Playwright / Playwright MCP、录制与脚本复用、数据库二次校验、Jenkins 多项目构建与部署、SVN / Git",
      size: "small-square",
      coverImage: "",
      icon: "terminal",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 7,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-ai-qa",
      sectionId: topLevelBlockSectionId,
      title: "AI QA 与知识工程",
      subtitle: "",
      description: "Codex、Claude Code、需求分析状态机、用例与报告生成、测试知识库、历史缺陷沉淀、禅道闭环",
      size: "small-square",
      coverImage: "",
      icon: "cpu",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 8,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-data",
      sectionId: topLevelBlockSectionId,
      title: "数据核对与定位",
      subtitle: "",
      description: "MySQL 数据查询与核对、日志分析、配置表校验、问题归属判断",
      size: "small-square",
      coverImage: "",
      icon: "database",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 9,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "skills-collab",
      sectionId: topLevelBlockSectionId,
      title: "质量协作与工具",
      subtitle: "",
      description: "测试任务拆解、版本进度跟进、缺陷闭环、禅道、TAPD",
      size: "small-square",
      coverImage: "",
      icon: "users",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 10,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-experience",
      sectionId: topLevelBlockSectionId,
      title: "工作经历",
      subtitle: "Work Experience",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "briefcase",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "experience",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 11,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "job-baismgs",
      sectionId: topLevelBlockSectionId,
      title: "福州白松果网络",
      subtitle: "测试工程师 · 2024 年 8 月 - 至今",
      description: "负责多个 Web 项目前台及管理后台的全流程质量保障，覆盖用户、充提、活动、任务与佣金等核心模块。作为测试团队 AI QA 全链路推进主要负责人，基于 Codex Skills + Playwright 建设七阶段工作流、自动化执行与可追溯证据链，并优化 Jenkins 多项目构建流程。",
      size: "wide",
      coverImage: "",
      icon: "building",
      badge: "当前",
      href: "",
      actionType: "modal",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        modalTitle: "福州白松果网络 · 测试工程师",
        modalSubtitle: "2024 年 8 月 - 至今",
        modalBody: "• 负责公司多个 Web 项目前台及管理后台的功能测试、接口验证与数据核验，覆盖用户、充提、活动、任务、佣金等核心模块；围绕业务规则、状态流转及异常边界开展验证与版本验收。\n\n• 贯穿需求评审、测试执行、缺陷跟踪和回归验收；结合接口响应、业务日志及数据库数据定位问题，协同产品与研发推动修复闭环。\n\n• 作为测试团队 AI QA 全链路推进主要负责人，基于 Codex Skills 推动需求分析、用例生成、知识资产沉淀、自动化执行和数据验证；建设内部测试知识库，沉淀业务规则、历史缺陷及测试经验，支持团队复用与新人快速上手。\n\n• 基于 Playwright 搭建 Web 自动化测试体系，以“录制 + 脚本”覆盖核心业务流程，并结合数据库进行二次校验，提升回归效率与数据准确性。\n\n• 优化 Jenkins 构建流程及内部测试工具，整合多项目构建与部署流程，减少重复人工操作。\n\n代表项目\n\n• QA 自动化工作流（Playwright + Codex Skills）：按 agent_docs / custom-skills / scripts / references / templates / workflow-runner 分层管理规则、技能、脚本、知识资产、模板和执行器，解决流程分散、经验难复用、自动化与交付物割裂问题。\n\n• 七阶段流程：编排“需求分析 → 测试用例 → 脚本自动化 → 交付用例 → Bug 登记 → Bug 验证 → 知识库同步”，并通过 Python 状态机控制需求分析步骤和人工确认门禁。\n\n• 执行与交付：使用 Playwright 结合数据库核验，统一采集截图、日志和 HTML Report；生成并回填 Excel 测试报告与 summary.json，形成可追溯证据链。\n\n• 资产与闭环：沉淀业务规则、页面结构、模块基线、弱网及充提 / VIP 等专项能力，接入禅道 Bug 查重、登记、复测和收口。\n\n• 游戏聚合平台（类 Steam）：覆盖账号、推荐、试玩、充值、评论、排行榜、论坛等模块，围绕“注册 → 发现 → 试玩 → 充值 → 互动”主链路开展端到端验收。\n\n• AI 翻译平台：覆盖“上传 → 选语 → 翻译 → 修正 → 批量导出 → 知识库复用”流程，重点检查文件处理、术语复用、多语言结果和异常流程的一致性。"
      },
      isVisible: true,
      isFeatured: false,
      sortOrder: 12,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "job-zhuque",
      sectionId: topLevelBlockSectionId,
      title: "福州朱雀网络有限公司",
      subtitle: "测试工程师 → 系统策划 · 2017 年 6 月 - 2024 年 5 月",
      description: "公司内由测试工程师晋升为系统策划。测试阶段负责计划与用例、任务拆解、MySQL 数据核验、禅道闭环及 AirtestProject 自动化；策划阶段承担需求可测性分析、UI 与配置资源校验、Unity / UGUI 问题定位和版本验收。",
      size: "wide",
      coverImage: "",
      icon: "building",
      badge: "7 年",
      href: "",
      actionType: "modal",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        modalTitle: "福州朱雀网络有限公司 · 测试工程师 → 系统策划",
        modalSubtitle: "测试工程师：2017 年 6 月 - 2021 年 4 月 ｜ 系统策划：2021 年 5 月 - 2024 年 5 月",
        modalBody: "系统策划阶段\n\n• 同步承担需求可测性分析与版本验收，基于玩法规则、配置表和状态流转拆解验证场景，跟进客户端 / 服务端实装及问题闭环。\n\n• 负责正式版 UI 与配置资源的版本校验，经 SVN / Git 流转至工程后核对资源一致性、配置正确性和 Unity 接入表现。\n\n• 跟进客户端 / 服务端配置与功能实装，结合 UGUI 排查界面显示、交互和资源问题，协助研发定位并验证修复结果。\n\n• 完成主要界面改版、副玩法（类 CF 生化模式）及后台管理工具的功能、配置与流程验收，推动问题在上线前闭环。\n\n测试工程师阶段\n\n• 制定并执行游戏测试计划，覆盖用例设计、环境搭建、数据准备、结果反馈与版本验收。\n\n• 拆解测试任务、分配人员、跟进进度与质量把控，协助团队提升版本交付效率。\n\n• 使用 MySQL 查询核对数据，经禅道反馈复查问题，并用 AirtestProject 完成自动化验证。\n\n• 独立分析配置表定位问题归属，降低程序与策划排查成本。\n\n代表项目\n\n• 《小米超神》：负责内测至正式上线阶段的系统功能、更新后台和热更新链路验证，覆盖测试准备、缺陷跟踪、回归验收以及线上更新包测试与发布。\n\n• 代号 M《重构·阿塔提斯》：参与解压更新、兼容性、弱网及海外版本专项测试；围绕商业化活动、热更新、生化玩法、社交 / 社团 / 战队、观战、商城 / 交易所、陪玩等模块开展规则校验、配置检查、功能回归与版本验收。\n\n• 代号 DL：参与模拟经营、建筑、基地养成与角色 / 僵尸技能等模块的配置校验和功能验证，检查 Unity 行为树及模型、特效、动作、音效组合表现。"
      },
      isVisible: true,
      isFeatured: false,
      sortOrder: 13,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "job-tianshang",
      sectionId: topLevelBlockSectionId,
      title: "福州天尚科技有限公司",
      subtitle: "产品策划 · 2016 年 4 月 - 2017 年 5 月",
      description: "参与 VR 内容平台《玩 VR》的需求梳理、版本体验验收与问题反馈。负责新接入游戏及内容更新的上线检查，支撑累计 600+ 款游戏内容及软件内付费购买功能稳定交付。",
      size: "wide",
      coverImage: "",
      icon: "building",
      badge: "",
      href: "",
      actionType: "modal",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        modalTitle: "福州天尚科技有限公司 · 产品策划",
        modalSubtitle: "2016 年 4 月 - 2017 年 5 月",
        modalBody: "• 参与 VR 内容平台《玩 VR》的需求梳理、版本体验验收与问题反馈，围绕功能流程、内容展示和付费购买接入开展上线前检查。\n\n• 结合 VR 平台竞品调研与玩家反馈，补充体验问题、异常场景和重点设备验证清单，跟进功能优化结果。\n\n• 负责新接入游戏及内容更新的上线检查，核对素材、展示信息、专题活动与设备专区内容，发现问题后推动修正。\n\n项目成果：参与《玩 VR》全网上线质量保障，支撑累计 600+ 款游戏内容（正版 30+）及软件内付费购买功能稳定交付。"
      },
      isVisible: true,
      isFeatured: false,
      sortOrder: 14,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-travel",
      sectionId: topLevelBlockSectionId,
      title: "旅行足迹",
      subtitle: "Travel Footprint",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "map",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "travel",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 15,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "travel-footprint",
      sectionId: topLevelBlockSectionId,
      title: "走过的每一个地方，都是故事",
      subtitle: "",
      description: "把抵达过的地方留在地图上，也把沿途的故事慢慢写下来。",
      size: "full-wide",
      coverImage: "",
      icon: "map",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        travelLocations: [
          { city: "福州", province: "福建", note: "常驻地 · 有福之州", longitude: 119.3, latitude: 26.08 },
          { city: "贵州", province: "贵州", note: "已到访", longitude: 106.71, latitude: 26.6 },
          { city: "成都", province: "四川", note: "已到访", longitude: 104.07, latitude: 30.67 },
          { city: "潮汕", province: "广东", note: "已到访", longitude: 116.68, latitude: 23.35 },
          { city: "江西", province: "江西", note: "已到访", longitude: 115.86, latitude: 28.68 }
        ]
      },
      sortOrder: 16,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-projects",
      sectionId: topLevelBlockSectionId,
      title: "个人项目",
      subtitle: "Personal Projects",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "terminal",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "projects",
        titleAlign: "left",
        titleSize: "lg"
      },
      sortOrder: 17,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "personal-projects-showcase",
      sectionId: topLevelBlockSectionId,
      title: "个人项目",
      subtitle: "",
      description: "",
      size: "full-wide",
      coverImage: "",
      icon: "terminal",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        projects: [
          {
            title: "CineScope",
            description: "影视内容聚合展示平台，通过自动化数据管线持续更新分类、评分、票房、热度与预告片数据。",
            eyebrow: "FILM · 01",
            href: "https://github.com/lrwei91/CineScope",
            liveHref: "https://lrwei91.github.io/CineScope/#tv_cn",
            icon: "film",
            tone: "mint"
          },
          {
            title: "fund-tracker-desktop",
            description: "Electron 桌面行情与持仓工具，集成指数、自选股、资金流、研究卡、财经快讯和独立持仓浮窗。",
            eyebrow: "MARKET · 02",
            href: "https://github.com/lrwei91/fund-tracker-desktop",
            icon: "market",
            tone: "blue"
          },
          {
            title: "Lottery",
            description: "体彩可视化分析与智能预测工具，包含历史走势、Canvas 图表、多策略回测与世界杯预测。",
            eyebrow: "DATA · 03",
            href: "https://github.com/lrwei91/Lottery",
            liveHref: "https://bet.lrwei91.online/#dlt",
            icon: "data",
            tone: "yellow"
          }
        ]
      },
      sortOrder: 18,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-education",
      sectionId: topLevelBlockSectionId,
      title: "教育经历",
      subtitle: "Education",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "book",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "education",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 19,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "education-content",
      sectionId: topLevelBlockSectionId,
      title: "福州软件职业技术学院",
      subtitle: "计算机应用技术 · 大专 · 2014 届",
      description: "",
      size: "wide",
      coverImage: "",
      icon: "book",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 20,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-other",
      sectionId: topLevelBlockSectionId,
      title: "其他",
      subtitle: "Additional",
      description: "",
      size: "section-text",
      responsiveSizes: {
        desktop: "section-text",
        mobile: "section-text"
      },
      coverImage: "",
      icon: "info",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        sourceSectionId: "other",
        titleAlign: "left",
        titleSize: "md"
      },
      sortOrder: 21,
      isVisible: true,
      isFeatured: false,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "other-content",
      sectionId: topLevelBlockSectionId,
      title: " ",
      subtitle: "",
      description: "语言：普通话（母语）\n\n自驱方向：持续关注 AI 工具链、测试自动化与持续集成，日常通过 Codex Skills、Playwright 与可复用脚本持续完善 QA 工作流。",
      size: "wide",
      coverImage: "",
      icon: "",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: {
        textVariant: "plain",
        textAlign: "left",
        textBold: false
      },
      isVisible: true,
      isFeatured: false,
      sortOrder: 22,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "github-link",
      sectionId: topLevelBlockSectionId,
      title: "GitHub",
      subtitle: "",
      description: "开源项目与作品集",
      size: "small-square",
      coverImage: "",
      icon: "github",
      badge: "",
      href: "https://github.com/lrwei91",
      actionType: "link",
      openInNewTab: true,
      backgroundColor: "",
      textColor: "",
      metadata: {},
      isVisible: true,
      isFeatured: false,
      sortOrder: 23,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-now",
      sectionId: topLevelBlockSectionId,
      title: "此刻",
      subtitle: "Now",
      description: "",
      size: "section-text",
      responsiveSizes: { desktop: "section-text", mobile: "section-text" },
      coverImage: "",
      icon: "sparkle",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { sourceSectionId: "now", titleAlign: "left", titleSize: "md" },
      isVisible: false,
      isFeatured: false,
      sortOrder: 0,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "now-status",
      sectionId: topLevelBlockSectionId,
      title: "此刻 NOW",
      subtitle: "",
      description: "",
      size: "full-wide",
      responsiveSizes: { desktop: "full-wide", mobile: "full-wide" },
      coverImage: "",
      icon: "sparkle",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { nowStatus: { headline: "", body: "", mood: "", location: "", tags: [], updatedAt: "" } },
      isVisible: false,
      isFeatured: false,
      sortOrder: 0,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-media",
      sectionId: topLevelBlockSectionId,
      title: "最近在看 / 玩 / 听",
      subtitle: "Media Shelf",
      description: "",
      size: "section-text",
      responsiveSizes: { desktop: "section-text", mobile: "section-text" },
      coverImage: "",
      icon: "book-open",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { sourceSectionId: "media", titleAlign: "left", titleSize: "md" },
      isVisible: false,
      isFeatured: false,
      sortOrder: 14,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "media-shelf",
      sectionId: topLevelBlockSectionId,
      title: "最近在看 / 玩 / 听",
      subtitle: "",
      description: "",
      size: "full-wide",
      responsiveSizes: { desktop: "full-wide", mobile: "full-wide" },
      coverImage: "",
      icon: "book-open",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { mediaItems: [] },
      isVisible: false,
      isFeatured: false,
      sortOrder: 14,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "text-photos",
      sectionId: topLevelBlockSectionId,
      title: "照片故事",
      subtitle: "Photo Stories",
      description: "",
      size: "section-text",
      responsiveSizes: { desktop: "section-text", mobile: "section-text" },
      coverImage: "",
      icon: "image",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { sourceSectionId: "photos", titleAlign: "left", titleSize: "md" },
      isVisible: false,
      isFeatured: false,
      sortOrder: 16,
      createdAt: now,
      updatedAt: now
    },
    {
      id: "photo-stories",
      sectionId: topLevelBlockSectionId,
      title: "照片故事",
      subtitle: "",
      description: "",
      size: "full-wide",
      responsiveSizes: { desktop: "full-wide", mobile: "full-wide" },
      coverImage: "",
      icon: "image",
      badge: "",
      href: "",
      actionType: "none",
      openInNewTab: false,
      backgroundColor: "",
      textColor: "",
      metadata: { photoStories: [] },
      isVisible: false,
      isFeatured: false,
      sortOrder: 16,
      createdAt: now,
      updatedAt: now
    }
  ],
  theme: {
    primaryColor: "#b23c22",
    backgroundColor: "#f6f3ec",
    cardBackground: "#fcfaf5",
    textColor: "#201d18",
    mutedTextColor: "#6f6a5e",
    borderColor: "#ddd6c8",
    cardRadius: "md",
    cardShadow: "none",
    fontFamily: "system"
  },
  settings: {
    projectName: "Bio Template Editor",
    siteTitle: "Lin Rongwei · Portfolio",
    siteDescription: "Lin Rongwei - QA Engineer (Game / Web Testing · Automation · Version Quality)",
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    seoTitle: "",
    seoDescription: "",
    seoCanonicalUrl: "",
    seoOgImage: "",
    seoOgImageAlt: "",
    enableImagePreview: true,
    enableAnimation: true,
    enablePublicShare: true,
    languages: {
      isEnabled: false,
      mainLocale: "en",
      languages: [
        { code: "en", label: "English", isEnabled: true, sortOrder: 1 }
      ]
    },
    variants: {
      isEnabled: false,
      mainVariantId: "main",
      variants: [
        {
          id: "main",
          name: "Main version",
          accessCode: "",
          isEnabled: true,
          allowSeoIndex: true,
          sortOrder: 1,
          mainLocale: "en",
          languages: [{ code: "en", label: "English", isEnabled: true, sortOrder: 1 }],
          languageSettings: { en: { isEnabled: true } }
        }
      ]
    }
  },
  contentVariants: {},
  updatedAt: now,
  revision: 1
};

export function getDefaultSiteConfig(languageTag?: string | null): SiteConfig {
  const config = structuredClone(defaultSiteConfig);
  if (!languageTag?.toLowerCase().startsWith("zh")) return config;

  // 默认配置已为中文内容，不再覆盖 profile 和 blocks
  config.settings = {
    ...config.settings,
    projectName: "个人主页编辑器",
    siteTitle: "林荣威 · 个人主页",
    siteDescription: "林荣威的个人主页 - 测试工程师（游戏 / Web 业务测试 · 自动化 · 版本质量）",
    languages: {
      isEnabled: false,
      mainLocale: "zh-CN",
      languages: [{ code: "zh-CN", label: "中文", isEnabled: true, sortOrder: 1 }]
    },
    variants: {
      isEnabled: false,
      mainVariantId: "main",
      variants: [{
        id: "main",
        name: "主版本",
        accessCode: "",
        isEnabled: true,
        allowSeoIndex: true,
        sortOrder: 1,
        mainLocale: "zh-CN",
        languages: [{ code: "zh-CN", label: "中文", isEnabled: true, sortOrder: 1 }],
        languageSettings: { "zh-CN": { isEnabled: true } }
      }]
    }
  };
  return config;
}
